apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-chain-app
  labels:
    app: supply-chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supply-chain
  template:
    metadata:
      labels:
        app: supply-chain
      annotations:
        # This tells Prometheus to automatically find your metrics!
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: app
        image: supply-chain-app:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: supply-chain-service
  labels:
    app: supply-chain
spec:
  selector:
    app: supply-chain
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
